on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
    - name: Prepare
      run: |
        apk update
        apk add go git
        go version

    - name: Pull
      run: |
        git clone https://github.com/fruitgum/nexus-helm-push.git

    - name: Build
      run: |
        ls
        cd nexus-helm-push
        go mod tidy
        go build -o nexus-helm-push
        export GOOS=windows
        go build -o nexus-helm-push.exe

    - name: Upload-Windows
      uses: actions/upload-artifact@v4
      with:
        name: nexus-helm-push.exe
        path: nexus-helm-push/nexus-helm-push.exe
        compression-level: 0
        overwrite: true

    - name: Upload-Linux
      uses: actions/upload-artifact@v4
      with:
        name: nexus-helm-push
        path: nexus-helm-push/nexus-helm-push
        compression-level: 0
        overwrite: true
