on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:  golang:alpine3.20

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: | 
        cd ${{ github.repository }}
        if [ ${{ matrix.os }} == 'windows-latest' ]; then
          GOOS=windows GOARCH=amd64 go build 
        else
          GOOS=linux GOARCH=amd64 go build 
        fi

    - name: Upload Win Binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.repository }}.exe
        path: /go/${{ github.repository }}.exe
        
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.repository }}
        path: /go/${{ github.repository }}
