on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:  golang:alpine3.20

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Pull
      run: |
        apk update 
        apk add git
        git clone https://github.com/fruitgum/nexus-helm-push.git

    - name: Build
      run: | 
        cd nexus-helm-push
        if [ ${{ matrix.os }} == 'windows-latest' ]; then
          GOOS=windows GOARCH=amd64 go build 
        else
          GOOS=linux GOARCH=amd64 go build 
        fi

    - name: Upload Win Binary
      uses: actions/upload-artifact@v3
      with:
        name: nexus-helm-push.exe
        path: /go/nexus-helm-push.exe
        
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v3
      with:
        name: nexus-helm-push
        path: /go/nexus-helm-push
